site_name: lswtrue
site_author: 李胜伟
copyright: Copyright @ 2024 李胜伟
site_url: https://lswtrue.github.io/
theme:
  name: mkdocs

nav:
  - 首页: index.md
  - 《修真与精神疾病》:
    - 前言: xiuzhen/0前言.md
    - 整体框架: xiuzhen/1整体框架.md
    - 基础假设: xiuzhen/2基础假设.md
    - 引经据典: xiuzhen/3引经据典.md
    - 通用打坐: xiuzhen/4通用打坐.md
    - 身体变化: xiuzhen/5身体变化.md
    - 笔者改进: xiuzhen/6笔者改进.md
    - 性命双修: xiuzhen/7性命双修.md
    - 前额木僵: xiuzhen/8前额木僵.md
    - 猜想:幻视: xiuzhen/9猜想-幻视.md
    - 猜想:幻听: xiuzhen/10猜想-幻听.md
    - 猜想:情绪起伏: xiuzhen/11猜想-情绪起伏.md
  # - 《强迫思维、社会化、现象学》
  # - 《社会化、匹配机制、库存系统》